### ISSUE TITLE
frontend module cannot be compiled

### ISSUE THREAD

**Issue by KengoTODA** [WorksApplications/asset-wizard#2]
When I tried to compile `frontend` module by yarn 1.6.0, it reports error like below:

```
./node_modules/@material-ui/icons/utils/createSvgIcon.js
Module not found: Can't resolve '@material-ui/core/SvgIcon' in '.../asset-wizard/frontend/node_modules/@material-ui/icons/utils'
```

I guess we need to update `package.json` and `yarn.lock` to refer latest build of material-ui next.

**Comment by KengoTODA** [comment]
I reproduced this build failure on [Travis CI](https://www.travis-ci.com/WorksApplications/asset-wizard/builds/73275417#L882).

**Comment by ayusun** [comment]
I have made some changes,should fix the problems

**Comment by KengoTODA** [comment]
Yes now it's working! Thanks!
